#
#    ████████╗░█████╗░██╗░░██╗░█████╗░███████╗██████╗░░█████╗░
#    ╚══██╔══╝██╔══██╗╚██╗██╔╝██╔══██╗╚════██║╚════██╗██╔══██╗
#    ░░░██║░░░██║░░██║░╚███╔╝░╚█████╔╝░░░░██╔╝░░███╔═╝╚██████║
#    ░░░██║░░░██║░░██║░██╔██╗░██╔══██╗░░░██╔╝░██╔══╝░░░╚═══██║
#    ░░░██║░░░╚█████╔╝██╔╝╚██╗╚█████╔╝░░██╔╝░░███████╗░█████╔╝
#    ░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝░╚════╝░░░╚═╝░░░╚══════╝░╚════╝░
#
# Автор - Tox_8729
# Телеграмм канал - https://t.me/vdev1337
# Телеграмм создателя - @Tox_8729
# Если есть баги или дюпы пишите в тг
# Спасибо за использование данного плагина!
#

# Раз в сколько времени будет обновляться скупщик в формате чч.мм.сс
update-interval: "01.00.00"

# Настройка звуков
sounds:
  # Когда обновился скупщик
  update-seller: ENTITY_PLAYER_LEVELUP
  # Когда продал предмет
  sell: ENTITY_VILLAGER_YES
  # Когда нет предмета для продажи
  no-items: ENTITY_VILLAGER_NO

messages:
  sell: "<#70B3CD>✔ <gray>| <white>Вы продали <#70B3CD>{amount} {item} <white>за <#70B3CD>{price}$"
  sell-all: "<#70B3CD>✔ <gray>| <white>Вы продали <#70B3CD>{total} {item} <white>за <#70B3CD>{total_money}$"
  no-items: "<#70B3CD>✘ <gray>| <white>У вас нет этого предмета!"
  update-seller:
    - ""
    - "<#70B3CD>⌚ <gray>| <white>Скупщик обновил <#70B3CD>ассортимент <white>предметов"
    - ""