name: MiniBuyer
version: '${project.version}'
main: ua.vdev.minibuyer.MiniBuyer
api-version: '1.20'
authors: [Tox_8729]
depend: [Vault, PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:7.0.1

commands:
  buyer:
  minibuyer:

permissions:
  minibuyer.admin:
    default: op
