#
#    ████████╗░█████╗░██╗░░██╗░█████╗░███████╗██████╗░░█████╗░
#    ╚══██╔══╝██╔══██╗╚██╗██╔╝██╔══██╗╚════██║╚════██╗██╔══██╗
#    ░░░██║░░░██║░░██║░╚███╔╝░╚█████╔╝░░░░██╔╝░░███╔═╝╚██████║
#    ░░░██║░░░██║░░██║░██╔██╗░██╔══██╗░░░██╔╝░██╔══╝░░░╚═══██║
#    ░░░██║░░░╚█████╔╝██╔╝╚██╗╚█████╔╝░░██╔╝░░███████╗░█████╔╝
#    ░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝░╚════╝░░░╚═╝░░░╚══════╝░╚════╝░
#
# Автор - Tox_8729
# Телеграмм канал - https://t.me/vdev1337
# Телеграмм создателя - @Tox_8729
# Если есть баги или дюпы пишите в тг
# Спасибо за использование данного плагина!
#

# Раз в сколько времени будет обновляться скупщик в формате чч.мм.сс
update-interval: "00.01.00"

# Названия основного меню
main-menu: "main-menu"

# Настройка звуков
sounds:
  # Когда обновился скупщик
  update-seller: ENTITY_PLAYER_LEVELUP;1.0;1.0
  # Когда продал предмет
  sell: ENTITY_VILLAGER_YES;0.8;1.2
  # Когда нет предмета для продажи
  no-items: ENTITY_VILLAGER_NO;1.0;0.8

# Сообщения
messages:
  no_permission: "<#E25822>✘ <gray>| <white>У вас нет прав"

  player_not_found: "<#E25822>✘ <gray>| <white>Игрок <#E25822>{player} <white>не найден"

  invalid_level: "<#E25822>✘ <gray>| <white>Уровень <#E25822>{level} <white>не существует. Максимум: <#E25822>{max_level}"

  invalid_number: "<#E25822>✘ <gray>| <white>Должно быть числом"

  level_set: "<#E25822>✔ <gray>| <white>Уровень <#E25822>{player} <white>установлен на <#E25822>{level}"

  items_added: "<#E25822>✔ <gray>| <white>Добавлено <#E25822>{amount} <white>предметов игроку <#E25822>{player}<white>"

  reload_success: "<#E25822>✔ <gray>| <white>Плагин перезагружен за <#E25822>{time} <white>мс"

  sell: "<#E25822>✔ <gray>| <white>Вы продали <#E25822>{amount} {item} <white>за <#E25822>{price}$"

  sell-all: "<#E25822>✔ <gray>| <white>Вы продали <#E25822>{total} {item} <white>за <#E25822>{total_money}$"

  no-items: "<#E25822>✘ <gray>| <white>У вас нет этого предмета"

  update-seller:
    - ""
    - "<#E25822>⌚ <gray>| <white>Скупщик обновил <#E25822>ассортимент <white>предметов"
    - ""

  admin_usage:
    - "<#E25822>Использование команды:"
    - ""
    - " <gray>- <#E25822>/minibuyer reload <gray>- <white>Перезагрузить плагин"
    - " <gray>- <#E25822>/minibuyer level set [ник] [лвл] <gray>- <white>Установить уровень игроку"
    - " <gray>- <#E25822>/minibuyer items add [ник] [кол.] <gray>- <white>Добавить проданные предметы"
    - ""